### ISSUE TITLE
Encoded video play speed(frame interval) seems depended on fps.

### ISSUE THREAD

**Issue by hongryeol-lee** [secile/OpenH264Lib.NET#12]
Hi, 
Thank you for your project.

I encoded avi file using `public int Encode(Bitmap bmp);`
and played this video on mediaplayer(windows).
but, video files encoded with different fps have different play speeds.
It seems to vary according to fps.
I want to keep the playing speed constant even if the fps are different.
Can you help me?

I used the timer to encode the screen capture in real time as follows.

`_timer.Interval = 1000 / fps;  
_timer.Tick += (sender, e) =>
            {
                try
                {
                    Bitmap screen = _provider.Capture();
                    _encoder.Encode(screen);
                }
                catch
                { }
            };`

**Comment by secile** [comment]
I'm sorry for late, very late reply.
I think you do not need the answer anymore, but anyway I answer.

It is natural that different fps have different playback speed.
* 10 bitmaps with 1 fps -> playback in 10 sec.
* 10 bitmaps with 10 fps -> playback in 1 sec.

To keep playback speed constant,
you need to change the number of bitmaps you supply.
* 10 bitmaps with 1 fps -> playback in 10 sec.
* 100 bitmaps with 10 fps -> playback in 10 sec.
* 300 bitmaps with 30 fps -> playback in 10 sec.

If this does not answer your question, please ask again.
Thank you.

**Comment by hongryeol-lee** [comment]
I got it, Thank you!!
