### ISSUE TITLE
H264 Stream freezes when generating IDR Frames

### ISSUE THREAD

**Issue by NoOverflow** [secile/OpenH264Lib.NET#13]
Hi, this is a follow up of the following issue (https://github.com/sipsorcery/sipsorcery/issues/317)
I noticed some huge freezes using your wrapper to send H264 frames to a WebRTC stream,
the behavior is described in the issue mentionned before.

I initialize the stream like so 
`this.H264Encoder = new Encoder("openh264-2.1.1-win64.dll");`
` this.H264Encoder.Setup(width, height, width * height * 3 / 2 * 8, fps, 2.0F, onEncode);`

I changed wrapper and used X264.net and the issue disappeared. Do you have any idea where that freeze could come from ? 
Thanks

**Comment by secile** [comment]
Hello. Thank you for your question.
But I can not awnser your question because I am not familiar with WebRTC
and I am not able to recreate your problem. I am very sorry for you.

I remain this issure open until anyone awnser your question.

**Comment by NoOverflow** [comment]
Not related to your library and has been fixed, sorry about that
