### ISSUE TITLE
"Could not load file or assembly 'OpenH264Lib.dll' or one of it's dependencies" message on Win 10 vbox/vmware

### ISSUE THREAD

**Issue by johnnyboins91** [secile/OpenH264Lib.NET#16]
Hey, first of all, thanks for great wrapper! Working perfectly on host side, but when i try to run my app (that's using this wrapper) on vbox/vmware virtual machine, i get "Could not load file or assembly 'OpenH264Lib.dll' or one of it's dependencies" message.. Which is a bit weird because both OS's are same. I'm pretty sure that problem is on my side but since i'm not experienced in c# i'm not sure where to look/how to resolved this... So any help would be greatly appreciated! :)

**Comment by secile** [comment]
Hello. Thank you for your question.  
The exception is 'BadImageFormatException'? If so, I think it is x86/x64 problem.  
Does your PC's os is x86/x64?  
Does your virtual machine's os is x86/x64?
  
My sample uses 'openh264-1.7.0-win32.dll', so my sample is for x86. If you are going to use 'openh264-x.x.x-win64.dll', you have to build 'OpenH264Lib.dll' and your app as x64.

**Comment by johnnyboins91** [comment]
Hey, thanks for reply!
Here's full exception text (without Loaded Assemblies section, but i can include that if needed):
```
************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'OpenH264Lib.dll' or one of its dependencies. The specified module could not be found.
File name: 'OpenH264Lib.dll'
   at Client.Views.Preview.Setup()
   at Client.Views.Preview..ctor() in C:\Projects\SampleApp\Client\Views\Preview.cs:line 42
   at Client.Views.Settings.Connect_Click(Object sender, EventArgs e) in C:\Projects\SampleApp\Client\Views\Settings.cs:line 63
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Both systems are Win 10 x64, only difference is that my host is Enterprise (activated) and guest/vbox is Pro (not activated). Not sure if this could be the problem?
I've seen that samples are for x86 but as pointed out, it's working perfectly on host (without exception or anything), without the need to change anything...

I'll try to get another laptop/desktop to try running the app but essentially it would make development a lot easier and quicker if i could get this to work on vbox.

Sorry for bothering you with this, especially because i know the problem is on my side... but i really appreciate your response and willingness to help :)
Thanks!

**Comment by secile** [comment]
Thank you for your information.  
The exception is 'FileNotFoundException'. That means your app is not able to find 'OpenH264Lib.dll'.

You have to add reference to 'OpenH264Lib.dll' (or add dependency to OpenH264Lib project) in your app's project property.
Did you do it?

**Comment by johnnyboins91** [comment]
Hey, sorry for late reply. 
I did add the reference to dll file, i guess without adding it, it wouldn't work on host in the first place nor it would allow me to use it inside my project. This should be correct as it gets copied to build dir (currently Debug) when i build the app.

One thing tho, as i didn't know what else to do, i tried installing Visual Studio on my guest and tried building app from there and it worked now (both newly built and one i copied from host).. but this is not a real solution...

**Comment by secile** [comment]
Next, please check 'OpenH264Lib.dll' exists in the same folder of your SampleApp.exe.  
Normally, in case your SampleApp project add reference to 'OpenH264Lib.dll', dll will be copied to the same folder of exe automatically when build executed.
