### ISSUE TITLE
Missing dll

### ISSUE THREAD

**Issue by digitalprojections** [secile/OpenH264Lib.NET#3]
エラー	1	'C:\Users\XXX\source\repos\OpenH264Lib.NET\Debug\OpenH264Lib.dll' メタデータが見つかりませんでした。
it seems like a circular dependency. I need OpenH264Lib.dll to make my app work, while the sample project complains about the same missing dll
What to do?

**Comment by secile** [comment]
Hello. Thank you for your question.  
After opening 'Open H264 Lib.sln' Visual Studio solution file,
build OpenH264Lib project at first by clicking Visual Studio "Build" -> "Build OpenH264Lib" menu. (Not "Build" -> "Build Solution")  
Or from Solution Explorer, right click "OpenH264Lib" and build. (not OpenH264Sample!)
After build "OpenH264Lib", build "OpenH264Sample" project.

**Comment by digitalprojections** [comment]
Thanks for your quick response. I have done as you mentioned. All worked.

**Comment by secile** [comment]
I updated README.md. Thank you.
