### ISSUE TITLE
Exception thrown: 'System.IO.FileNotFoundException' 

### ISSUE THREAD

**Issue by digitalprojections** [secile/OpenH264Lib.NET#4]
Exception thrown: 'System.IO.FileNotFoundException' 
The very not found file is this:
OpenH264Lib.dll
Needless to say, it is included both in the folder and as embedded resource. Not working.
It is working perfectly on the development machine, but failing with the above mentioned error while remote debugging.
The target machine specs are very low:

[OS] Windows Embedded Standard 7 
[CPU] Intel(R) ATOM(TM) CPU E3825 @1.33GHz 
[メモリ] 2.00GB

I did all kind of research, but stuck with this issue now.

**Comment by bandy101** [comment]
same to me,How to solve it?

**Comment by digitalprojections** [comment]
Interesting. I have successfully developed a full scale face, eye, body detection library for similar device. Your problem is about the OS bits. Make sure your are using the dll that fits your OS. Otherwise, it will not be even discovered

**Comment by bandy101** [comment]
> Interesting. I have successfully developed a full scale face, eye, body detection library for similar device. Your problem is about the OS bits. Make sure your are using the dll that fits your OS. Otherwise, it will not be even discovered

build the  OpenH264Lib.dll and my project on window 7（32bit），run it on window10(64bit)
so can you upload a OpenH264Lib.dll for me

**Comment by digitalprojections** [comment]
I recommend you do it yourself. I don`t think it is a good idea to trust a dll from internet.

**Comment by bandy101** [comment]
> I recommend you do it yourself. I don`t think it is a good idea to trust a dll from internet.

Thank your reply,have a nice day.
