### ISSUE TITLE
How to use by AnyCPU?

### ISSUE THREAD

**Issue by a44281071** [secile/OpenH264Lib.NET#6]
How to use x64 platform?
Please add AnyCPU support document.

error by OpenH264Lib.log
“codec_api.h”: No such file or directory

**Comment by secile** [comment]
Hello. Thank you for your question.

1. How to use x64 platform.
Build 'OpenH264Lib' project as x64 platform.

2. How to use AnyCPU.
OpenH264Lib is C++/CLI project (not .NET), so platform is x86 or x68 only, you can't select AnyCPU.
In my understanding, only .NET language (C#, VB, etc) can select AnyCPU. 

3. “codec_api.h”: No such file or directory
I don't know why this error reported.
If you first use this project, please follow 'See Example' procedure in README.md.

If you still have problems, could you tell me your situation in more detail

**Comment by a44281071** [comment]
I selected  Release platform, and build OpenH264Lib, failed.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "codec_api.h"	OpenH264Lib	C:\Users\a4428\source\repos\OpenH264Lib.NET\OpenH264Lib\Stdafx.h	8	
Error (active)	E1696	cannot open source file "codec_app_def.h"	OpenH264Lib	C:\Users\a4428\source\repos\OpenH264Lib.NET\OpenH264Lib\Stdafx.h	9	
Error (active)	E1696	cannot open source file "codec_def.h"	OpenH264Lib	C:\Users\a4428\source\repos\OpenH264Lib.NET\OpenH264Lib\Stdafx.h	10	
Error (active)	E1696	cannot open source file "codec_ver.h"	OpenH264Lib	C:\Users\a4428\source\repos\OpenH264Lib.NET\OpenH264Lib\Stdafx.h	11	
Error	C1083	 Cannot open include file: 'codec_api.h': No such file or directory	OpenH264Lib	C:\Users\a4428\Source\Repos\OpenH264Lib.NET\OpenH264Lib\stdafx.h	8	

```
Only Debug|x86 can success.

**Comment by a44281071** [comment]
Or, Can you publish a repository Release pack? include release x86 and x64 OpenH264Lib dll.

**Comment by secile** [comment]
Oh, I understand your problem.

I will fix the problem within a few days. If you do yourself,
open OpenH264Lib's property page (not OpenH264Sample), and  
configure C/C++ -> General -> 'Additional Include Directories' with  
$(ProjectDir)\OpenH264Header\

**Comment by a44281071** [comment]
For my project:
I add a reference for OpenH264Lib.dll, copy openh264-2.0.0-win32.dll to bin/x86/debug.
throw an exception, how to use it?
```
Failed to load file or assembly "OpenH264Lib, Version = 1.0.7159.35179, Culture = neutral, PublicKeyToken = null" or one of its dependencies. Attempt to load an executable file that cannot be validated using link address information (IAT with more than two sections or one TLS section). (Exceptions from HRESULT: 0x80131019)
```

Yeah, fixed it. I used Cosutura.Fody, caused this exception. exclude OpenH264Lib in FodyWeavers.xml

**Comment by secile** [comment]
Hello. I fixed the problem that can not be able to make Release build.
I have never used Costura.Fody, I can not answer the reason why Exception happened.
I'm sorry.
