### ISSUE TITLE
How to display frames(I,P,B)

### ISSUE THREAD

**Issue by a44281071** [secile/OpenH264Lib.NET#7]
I need to display android screen in WPF, the data in WPF will received byte[] frame. 
But the byte[] frame will be (I,P,B), 
I find the method `YUV420PtoRGB()` , but just worked about P frame.
How to display all frames? Is it difficult?

**Comment by secile** [comment]
OpenH264Lib is only wrapper library, I'm not very detailed with how encode/decode works,
so, my answer may not be accurate.

In my understanding, to decode frame data, you do not have to worry about frame type(I, P, B).
All you have to do is only call decode method of decoder class.
If frame data have enough information, decode function returns Bitmap, if not enough, returns null.

P / B frame only have difference from I frame, so you can not decode image from only P or B frame.
OpenH264Lib decode function returns an image using the data received so far.
