### ISSUE TITLE
Lib can work with .h264 file or .h265 (hevc) ?

### ISSUE THREAD

**Issue by TiepHoangDev** [secile/OpenH264Lib.NET#8]
i read frames from stream rtsp camera, frames encode in H264 / H264+ / H265 / H265+ (by my setting). i want decode frame and send to web client to play video.
i can use this this lib to decode?
this is profile my frame:

> [STREAM]
> index=0
> codec_name=h264
> codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
> profile=Main
> codec_type=video
> codec_time_base=1/50
> codec_tag_string=[0][0][0][0]
> codec_tag=0x0000
> width=1920
> height=1080
> coded_width=1920
> coded_height=1088
> has_b_frames=0
> sample_aspect_ratio=1:1
> display_aspect_ratio=16:9
> pix_fmt=yuvj420p
> level=40
> color_range=pc
> color_space=bt709
> color_transfer=bt709
> color_primaries=bt709
> chroma_location=left
> field_order=progressive
> timecode=N/A
> refs=1
> is_avc=false
> nal_length_size=0
> id=N/A
> r_frame_rate=25/1
> avg_frame_rate=25/1
> time_base=1/1200000
> ...
thanks for reading!

**Comment by secile** [comment]
Thank you for your question.
OpenH264Lib.NET is only wrapper library of cisco's openh264, it is up to feature of openh264.
And as far as I know, openh264 is not able to encode/decode h265 frame.
So, this library is not able to encode/decode h265 frame.

**Comment by TiepHoangDev** [comment]
tks for reply!
